### ISSUE TITLE
About the evaluation metric RMSE

### ISSUE THREAD

**Issue by ShawnBIT** [neuro-ml/midline-shift-detection#2]
Hello. I noticed that for the computation of the evaluation metric RMSE, the predicted midline must have the same length of the ground truth midline, which may fail in some cases. For example, the predicted midline is shorter than the ground truth midline. In such cases, how to compute the RMSE? Look forward to your reply.

**Comment by maxme1** [comment]
Hi! Take a look at [this line](https://github.com/neuro-ml/midline-shift-detection/blob/da40c24880378c2e13061fb23608ed05b900922f/midline_shift_detection/predict.py#L43).
The length of both target and prediction are always equal to the height of the image - they are simply padded with `np.nan` where the line is undefined. So if you use `np.nanmean` instead of `np.mean` this should do the trick:
```python
def nanrmse(x, y):
    return np.sqrt(np.nanmean((x - y) ** 2))
```

**Comment by ShawnBIT** [comment]
Thanks for your reply. But I still have a concert about this form of metric. If the predicted midline is empty(for example, the limits are very short or even none), the midline coordinate tensor should be a tensor with np.nan for every position. Therefore, the RMSE and MAX are zero, which is obviously unreasonable. How do you consider this sort of case?

**Comment by maxme1** [comment]
In this case both rmse and max will also be `np.nan`, because the mean of an empty array is `nan`.
For this task we can't simply look at rmse or max deviation, we also need some sort of metric that describes how well we predict the limits of the midline, e.g. precision/recall.
E.g. in the case you described rmse will be `np.nan`, precision will be 1, but recall will be 0, so a bad recall will tell you that there's something wrong with this case.

**Comment by ShawnBIT** [comment]
Thank you. I got it.
